modid = "hexdim"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexdim/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexdim",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexxy Dimensions"
author = "walksanatora"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"  = 'pattern\(\s*"(?P<signature>[qwead]+)",\s*HexDir.(?P<startdir>\w+),\s*"(?P<name>[a-zA-Z0-9_\/]+)"' }
_per_world_value = "true"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/patterns/DimPatternRegistry.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../src"
package = "{src}/main/java/net/walksanator/hexdim"
